name: ag_keyboard
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  intl: ^0.20.2
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  logger: ^2.5.0
  path: ^1.8.2
  path_provider: ^2.0.11
  riverpod_annotation: ^2.6.1
  math_expressions: ^2.3.1
  fluttertoast: ^8.1.2
  flutter_staggered_grid_view: ^0.7.0


dependency_overrides:
  isar_flutter_libs:
    path: packages/isar_flutter_libs-3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  isar_generator: ^3.0.5
  build_runner: ^2.3.2
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
