name: ag_keyboard
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  intl: ^0.17.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  logger: ^1.3.0
  path: ^1.8.2
  path_provider: ^2.0.14
  math_expressions: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  isar_generator: ^3.0.5
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
